services:
  - type: web
    name: sentence-new
    runtime: node
    plan: free
    region: oregon
    branch: main
    autoDeployTrigger: checksPass
    buildCommand: npm run build
    preDeployCommand: npm run prisma:migrate:deploy
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: DATABASE_URL
        sync: false
      - key: UPLOAD_VERIFY_PASSWORD
        sync: false
