import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavPane from "./nav-pane";
import Providers from "./providers";
import ScrollToTopButton from "./scroll-to-top-button";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const themeInitScript = `
(() => {
	try {
		const storedTheme = window.localStorage.getItem("theme");
		const theme =
			storedTheme === "light" || storedTheme === "dark"
				? storedTheme
				: window.matchMedia("(prefers-color-scheme: dark)").matches
					? "dark"
					: "light";
		document.documentElement.dataset.theme = theme;
	} catch {}
})();
`;

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers>
					<div className="flex min-h-screen flex-col md:flex-row">
						<NavPane />
						<main className="order-2 flex-1 p-4 md:order-1 md:p-6">
							<section className="mt-4 md:mt-8">
								{children}
							</section>
						</main>
						<ScrollToTopButton />
					</div>
				</Providers>
			</body>
		</html>
	);
}
