import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="app-shell">
					<main className="app-main">
						<section className="app-content">{children}</section>
					</main>
					<aside className="nav-pane">
						<h2>メニュー</h2>
						<nav aria-label="ページリンク">
							<ul className="nav-list">
								<li>
									<Link href="/search">/search</Link>
								</li>
								<li>
									<Link href="/view">/view</Link>
								</li>
								<li>
									<Link href="/upload">/upload</Link>
								</li>
							</ul>
						</nav>
					</aside>
				</div>
			</body>
		</html>
	);
}
